### ISSUE TITLE
Training problem two batch.....

### ISSUE THREAD

**Issue by Ibrahimshaikh1258** [nicknochnack/YOLO-Drowsiness-Detection#3]
train: weights=yolov5s.pt, cfg=, data=dataset.yml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=500, batch_size=16, imgsz=320, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=2, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github:  YOLOv5 is out of date by 1 commit. Use `git pull` or `git clone [https://github.com/ultralytics/yolov5`](https://github.com/ultralytics/yolov5%60) to update.
fatal: cannot change to 'D:\Desktop\Ibrahim': No such file or directory
YOLOv5  2022-6-3 Python-3.10.0 torch-1.11.0+cpu CPU

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
Weights & Biases: run 'pip install wandb' to automatically track and visualize YOLOv5  runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir runs\train', view at http://localhost:6006/

Dataset not found , missing paths ['D:\\Desktop\\Ibrahim (main folder)\\object detection\\yolov5\\..data\\images']
Traceback (most recent call last):
  File "D:\Desktop\Ibrahim (main folder)\object detection\yolov5\train.py", line 670, in <module>
    main(opt)
  File "D:\Desktop\Ibrahim (main folder)\object detection\yolov5\train.py", line 565, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\Desktop\Ibrahim (main folder)\object detection\yolov5\train.py", line 106, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "D:\Desktop\Ibrahim (main folder)\object detection\yolov5\utils\general.py", line 484, in check_dataset
    raise Exception(emojis('Dataset not found \u274c'))
Exception: Dataset not found

**Comment by Ibrahimshaikh1258** [comment]
Two batch only train but any other batch not train....
